### ISSUE TITLE
Themenseiten: ToDo und Probleme

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#148]
Ich benutze auf der alten Seite ein Plugin, mit dem man Kategorien stylen kann, das habe ich jetzt auch auf der neuen Seite installiert. Falls du das einfach ersetzen kannst, kann es auch wieder raus.
![grafik](https://user-images.githubusercontent.com/6114076/46616129-254a1380-cb1a-11e8-8939-09fd4d43ca3b.png)

Damit ist es möglich, Bilder, oder formatierte Beschreibung auf eine Kategorieseite zu setzen. Ich habe hier die festen Verlinkungen zu Zen-reiki.de weggenommen, so dass wir wirklich auf der neuen Seite arbeiten.
Dabei tauchen folgende Probleme auf:
 * [x] Die **category muss bei mir themen** heißen, ich sehe im Moment nicht, wo ich das einstellen kann
https://reiki-lernen.de/category/buecher/
 * [x] Die Kategorieüberschrift muss weg, Seite beginnt obem mit einem Bild
 * [x] Auf der Kategorieseite werden 10 Kurzfassungen gezeigt mit Weiter Lesen,
 * [x] unten auf der Seite ist eine Blätteraktion, wenn es mehr als 10 Beiträge sind
 * [ ] Die Anzahl der Beiträge steht im jeweiligen Thema rechts im Menü dahinter

**Comment by springers54** [comment]
Das Problem mit den Kurzfassungen lässt sich einfach mit Wordpress-Bordmitteln umsetzen.
![grafik](https://user-images.githubusercontent.com/6114076/49492020-da692580-f856-11e8-8b61-d2e5293e7a9c.png)

Hier ein Beispiel. Man muss nur das `<!--more-->` in den Text an der Stelle reinsetzen. Alternativ gibt es ein Plugin Post Teaser, wobei ich Plugins so weit es geht vermeiden würde.
 * [x] Styling der Button, so dass diese auch rechtsbündig sind.
 * [x] Das Problem mit dem Blättern ist eigentlich auch per Wordpress lösbar, wie ich eben gegoogelt habe
Fehlt eigentlich nur das Styling der Blätternseiten, die ja Page2, Page3, ... heißen
![grafik](https://user-images.githubusercontent.com/6114076/49492339-27013080-f858-11e8-9728-befc9baa024c.png)

**Comment by springers54** [comment]
![grafik](https://user-images.githubusercontent.com/6114076/49524947-03b4a080-f8ad-11e8-83d4-8c7f6c0b29d3.png)
- [x] Bekommt man in der Übersichtsseite die untere Zeile mit den Rubriken, Kommentaren, ... komplett weg?
Man sieht an dem Beispiel, dass es nicht gut aussieht.  Es würde reichen, wenn das auf der Komplettseite zu sehen ist und auf den Übersichtsseiten nur der Anteasertext und der Buttom zum Weiterlesen.

**Comment by springers54** [comment]
- [ ] Für die Themenseite wirst du eine Vorlage schreiben müssen, die analog zur Kategorie alle Beiträge ausgibt. So wie im alten System. Ich komme da selbst leider nicht ran.
Alternativ muss man das wieder über ein Plugin lösen, würde ich aber gern drauf verzichten

**Comment by springers54** [comment]
Das Problem mit dem Wort Category im Link konnte ich lösen, der Link heißt jetzt themen, wie im alten System. Das ist für Google wichtig.

Es bleibt ein Problem offen, ich bekomme das Wort Kategorie bisher leider nicht weg im Titel der Seite.

- [x] Hier sollte es auch Themen heißen und nicht Kategorie

![grafik](https://user-images.githubusercontent.com/6114076/49564190-f76b2a80-f922-11e8-8203-7c2ed7486bfd.png)

**Comment by joergsteinhauer** [comment]
### Kurzfassung

Also zuerst sollte man im Artikel-HTML die Umbrüche korrekt erzeugen, es fehlten noch Leerzeile:
![image](https://user-images.githubusercontent.com/1843754/49896777-adb79e00-fe54-11e8-9849-e302d49a96c6.png)

Dabei fügt WP eben automatisch `p`-tags, somit entsteht schon mal der korrekte Abstand zwischen Button und Text:
![image](https://user-images.githubusercontent.com/1843754/49896787-b4deac00-fe54-11e8-8de6-9074aeea54b7.png)

------------------------

### Pagination 

> Fehlt eigentlich nur das Styling der Blätternseiten, die ja Page2, Page3, ... heißen

Habe es nun ähnlich wie schon woanders so gestylt:

![image](https://user-images.githubusercontent.com/1843754/49899094-02f6ae00-fe5b-11e8-8532-a863e39a6128.png)


------------------------

### Meta

Die Zeile mit " Zeile mit den Rubriken, Kommentaren" ist nun auf allen Kategorie-Übersichtsseiten weg, ging gerade nur über CSS. Ist weiterhin im DOM, aber ist ja nicht schlimm.

------------------------

### Themen Vorlage

> Für die Themenseite wirst du eine Vorlage schreiben müssen, die analog zur Kategorie alle Beiträge ausgibt...

Du meinst, es sollen auf https://reiki-lernen.de/themen/ analog zu https://zen-reiki.de/themen/ alle Beiträge angezeigt werden?

Ich nehme an, dieser verbliebene shortcode Schnipsel sorgt im alten System für diese Ausgabe, was wiederum ein Cherry-shortcode zu sein scheint:

```html
[posts_list numb=”15″ thumbs=”normal” post_content=”excerpt” order_by=”date” order=”DESC” link=”yes” tags=”no”Â Â ]
```

Ja, dann muss ich hier was entwickeln.

**Comment by springers54** [comment]
Also hier erst einmal ein Vergleich alte Seite und neue Seite:
![grafik](https://user-images.githubusercontent.com/6114076/49918907-01ea6e80-fea5-11e8-8bea-8690be18f301.png)
 * [x] Der Button zum Weiterlesen sollte nicht ganz so wuchtig sein, also in der Höne etwas kleiner
 * [x] Trennlinie zwischen den Beiträgen
 * [x] Könnten wir mal probieren, ob anstelle der gelben Farbe bei den Blättern Button graue Farbe verwendet werden kann für Text, Pfeil und Rahmen? Im Moment ist Gelb darüber und darunter irgendwie zu viel
![grafik](https://user-images.githubusercontent.com/6114076/49919169-f6e40e00-fea5-11e8-9fcd-0bc6edab90e6.png)
 * [ ] Offen bleibt die Reduzierung der Zahl der Beiträge auf einer Blätternseite. Durch die Lehrer sind es hier im Moment 12 Kurzfassungen. Das ist besonders für das Handy viel zu viel.

**Comment by springers54** [comment]
> Du meinst, es sollen auf https://reiki-lernen.de/themen/ analog zu https://zen-reiki.de/themen/ alle Beiträge angezeigt werden?

> 
> Ich nehme an, dieser verbliebene shortcode Schnipsel sorgt im alten System für diese Ausgabe, was wiederum ein Cherry-shortcode zu sein scheint:
> 
> [posts_list numb=”15″ thumbs=”normal” post_content=”excerpt” order_by=”date” order=”DESC” link=”yes” tags=”no”Â Â ]
> 
> Ja, dann muss ich hier was entwickeln.

**Dies ist im Moment eine der wichtigen größeren Baustellen für die Umstellung, die in deiner Hand liegt**

> Die Anzahl der Beiträge steht im jeweiligen Thema rechts im Menü dahinter

Hatten wir oben als Wunsch formuliert, würden wir aber drauf verzichten, da es nicht kriegsentscheidend ist

**Comment by joergsteinhauer** [comment]
Habe nun das mit der Ausgabe aller Beiträge implementiert. Es war der shortcode `posts_list`, welches wie vermutet aus dem Cherry-Framework kam. 
Habe hierzu also einfach den ganzen PHP Code aus Cherry kopiert und modifiziert, es funktioniert. Zumindest sehe ich keine Fehler. Denn ehrlich gesagt, sehe ich nicht bei jeder Code-Zeile durch, ich übernehme also keine Haftung dass das Zeug in jeder Situation funktioniert ;-) Wie gesagt, da fehlen mir die PHP bzw. WP-Kenntnisse - würde Sinn machen, dass heir nochmal ein erfahrener Entwickler drüber schaut.

Der Code ist heir zu finden: `wp-content/themes/zen-reiki/includes/functions/posts-list.php`

**Comment by springers54** [comment]
Prima, es zeigt zumindest etwas an. Werden wir mal beobachten
